### ISSUE TITLE
Addition of more metrics

### ISSUE THREAD

**Issue by ayush-tiwari26** [digital-alpha/Metric_Extraction#8]
Metrics ignored were: restricted cash, cash equivalents, cash, various taxable metrics like foreign tax credits, along with some complex and less common things like acquiring costs aggregates, valuation gain.
Need to list down more such metrics relevant to our case and add in config files.

**Comment by iamananya** [comment]
Benchmark metrices:
<b style="font-weight:normal;" id="docs-internal-guid-e4736c21-7fff-7862-68a6-b5f7beddadc4">

Name | Industry Benchmark | Significance
-- | -- | --
LTV / CAC | >3.0 | The Customer Lifetime Value to Customer Acquisition (LTV:CAC) ratio measures the relationship between the lifetime value of a customer, and the cost of acquiring that customer. The metric is computed by dividing LTV by CAC. It is a signal of customer profitability, and of sales and marketing efficiency.
Quick Ratio | > 4.0 | It assesses a company's ability to grow its recurring revenue despite the churn incurred. Essentially, the ratio compares the company's revenue inflows (new and expansion MRR) and its revenue outflows (churned MRR and contraction MRR) to show net revenue growth.
Net Dollar Revenue Retention | 114% | Retaining net revenue speaks to repeat business who are eventually turned into loyal customers & are even more likely to refer other customers to your SaaS product.
Magic Number | 1-1.5 | Magic Number indicates efficient and sustainable sales and marketing efficiency.
Growth Persistence | 89% (Median) | This measures the percentage of growth retained by the company over a year.

</b>

**Comment by ayush-tiwari26** [comment]
Added all the above listed metrics and was able to run the pipeline smoothly.
